### ISSUE TITLE
Regression introduced in v0.4 (commit dc583c) - breaking stickit (and potentially other scenarios)

### ISSUE THREAD

**Issue by mirko** [ybiquitous/backbone.deepmodel#228]
I noticed a regression (for my use case) introduced in v0.4.0, while it was working fine with v0.3.3.

The behaviour from my "user" point of view is, that it doesn't work anymore with the stickit bindings (https://github.com/NYTimes/backbone.stickit).
As a matter of fact, the DOM-form-elements don't get updated anymore on model changes, if the specified model attribute refers to a deep model attribute (like 'defaults.something').

I could narrow down the regression to commit dc583c6ec77ac475f4320e9192e85a047f29fa59, specifically this change: https://github.com/ybiquitous/backbone.deepmodel/commit/dc583c6ec77ac475f4320e9192e85a047f29fa59#diff-6341b72b80f47d0563ea885592419df4L280.

If I reintroduce that line in the latest release - v1.2.3 - it again works as expected:

```
diff --git a/dist/backbone.deepmodel.js b/dist/backbone.deepmodel.js
index 90fede5..7356358 100644
--- a/dist/backbone.deepmodel.js
+++ b/dist/backbone.deepmodel.js
@@ -306,6 +306,7 @@ var DeepModel = function (_Backbone$Model) {
 }(_backbone2.default.Model);
 
 exports.default = DeepModel;
+DeepModel.extend = Backbone.Model.extend;
 module.exports = exports['default'];
 
 /***/ }),
```

**Comment by mirko** [comment]
The commit after - 3887e67d67f89018d077064683a963ba79503839 - you basically reverted part of dc583c6ec77ac475f4320e9192e85a047f29fa59 (upgrade / downgrade of webpack) but didn't re-add above line. My guess would be, you either removed it by accident or forgot to re-add it while reverting the webpack part(?)

**Comment by ybiquitous** [comment]
Umm..., `Backbone.DeepModel.extend()` was moved to:

https://github.com/ybiquitous/backbone.deepmodel/blob/d0a6927af6b52f4eb9708ea6be77cf4c3b804ddf/lib/index.js#L38-L40

Here is `dist/backbone.deepmodel.js`:

```js
  }], [{
    key: 'extend',
    value: function extend() {
      var _Backbone$Model2;

      return (_Backbone$Model2 = _backbone2.default.Model).extend.apply(_Backbone$Model2, arguments);
    }
```

**Comment by ybiquitous** [comment]
I wrote an example on CodePen, which uses `backbone.deepmodel` and `backbone.stickit`.

This example seems to work, but is there something wrong?

https://codepen.io/ybiquitous/pen/wvvNObZ

**Comment by mirko** [comment]
Me, too :)

https://codepen.io/mirko2342/pen/YzzgyEx

vs

https://codepen.io/mirko2342/pen/xxxBwrV

(only difference is the version of backbone.deepmodel)

**Comment by ybiquitous** [comment]
Umm..., both seem to work on my browser (Firefox 70.0.1 on macOS) 🤔 ❓ 

Could you tell me your browser version?

**Comment by mirko** [comment]
Wait, really?
Even on my mobile one shows (as in: pre-select) "working" and the other one shows "doesn't work"
Using Firefox 70.0.1 (64-bit) on my computer and some random firefox version on Android.

**Comment by ybiquitous** [comment]
Oh, sorry. I confirmed the regression! 😅 👍

**Comment by ybiquitous** [comment]
I'm wondering why the `extend()` change cause the regression, but I confirmed the change on PR #229 can fix it.

**Comment by ybiquitous** [comment]
@mirko Please wait for a new release and then please verify the new version.

If the regression will not be fixed, please reopen the issue. 🙏

**Comment by ybiquitous** [comment]
Released! 🎉 

https://github.com/ybiquitous/backbone.deepmodel/releases/tag/v1.2.4
https://www.npmjs.com/package/backbone.deepmodel/v/1.2.4

**Comment by mirko** [comment]
Yay! Thank you so much! :)
